### ISSUE TITLE
账号密码是多少

### ISSUE THREAD

**Issue by cscsb** [Huxzhi/vue-router#1]

**Comment by Huxzhi** [comment]
写在后端代码里了

https://github.com/Huxzhi/vue-router/blob/2d6cd4f427b9d6d3b8f75bfde8907980c6e9862c/doc/12.a-%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1%E6%A1%88%E4%BE%8B-%E7%99%BB%E9%99%86%E5%90%8E%E5%8A%A8%E6%80%81%E6%B7%BB%E5%8A%A0%E8%B7%AF%E7%94%B1.md?plain=1#L128
